### ISSUE TITLE
typescript npm dependencies

### ISSUE THREAD

**Issue by OneCyrus** [sparkbitpl/i18n-ts#1]
we are looking into using this package. but unfortunately there's a hard dpendency on a specific outdated typescript dependency. would you mind to move it into devDependencies?

**Comment by jedrekfulara** [comment]
Sure, we'll update it.

**Comment by pdziuba** [comment]
done in https://github.com/sparkbitpl/i18n-ts/commit/0adb74532a8f753c4bd5f627ff92b0708894652d
