### ISSUE TITLE
lib file is missing in npm package

### ISSUE THREAD

**Issue by OneCyrus** [sparkbitpl/i18n-ts#2]
it looks like the transpiled version is missing in the npm package in 1.0.3. 

package.json references the following but this file is not in there.
```"main": "./lib/i18n.js"```

![image](https://user-images.githubusercontent.com/7747800/54115487-d0723800-43ec-11e9-923e-cf747d26f79f.png)

**Comment by pdziuba** [comment]
Yup, files weren't published because they are present in .gitignore.
Fixed in https://github.com/sparkbitpl/i18n-ts/commit/77a93ff777f3a72bafc6310f2090c0f1de8430ef
