### ISSUE TITLE
Split Translation in Multiple Files

### ISSUE THREAD

**Issue by johannesschobel** [sparkbitpl/i18n-ts#5]
Dear @pdziuba and @OneCyrus ,
i have a question and / or feature request for this package:
I would like to split my translation into several files in order to better maintain the structure. Consider, for example, this use-case:
```
\src
  \assets
    \translations
      \en
        general.ts
        mail.ts
        whatever.ts
```

The `general.ts` file may look like this:
```ts
export default {
   page: {
      title: 'My Fancy PageTitle',
      footer: '(c) 2019',
   },
   author: 'john doe',
}
```

And i would like to access the files like this `general.page.title` where the first segment (`general`) is the filename. What do you think about this?
All the best

**Comment by jedrekfulara** [comment]
Dear @johannesschobel 

I think you can achieve this right now, with a little bit of a boilerplate. You can split your translations the way you want and create an index.ts in the en directory like this:

```typescript
import general from "./general";
import mail from "./mail";

export default {
  general,
  mail, 
}
```
